/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    dangerouslyAllowSVG: true,
    remotePatterns: [
      { protocol: 'https', hostname: '**.theverge.com' },
      { protocol: 'https', hostname: '**.techcrunch.com' },
      { protocol: 'https', hostname: '**.wired.com' },
      { protocol: 'https', hostname: '**.engadget.com' },
      { protocol: 'https', hostname: '**.arstechnica.net' },
      { protocol: 'https', hostname: '**.arstechnica.com' },
      { protocol: 'https', hostname: '**.cnet.com' },
      { protocol: 'https', hostname: '**.zdnet.com' },
      { protocol: 'https', hostname: '**.gizmodo.com' },
      { protocol: 'https', hostname: '**.techradar.com' },
      { protocol: 'https', hostname: '**.mashable.com' },
      { protocol: 'https', hostname: '**.tomsguide.com' },
      { protocol: 'https', hostname: '**.technologyreview.com' },
      { protocol: 'https', hostname: '**.venturebeat.com' },
      { protocol: 'https', hostname: '**.bleepingcomputer.com' },
      { protocol: 'https', hostname: '**.securityweek.com' },
      { protocol: 'https', hostname: '**.krebsonsecurity.com' },
      { protocol: 'https', hostname: '**.threatpost.com' },
      { protocol: 'https', hostname: '**.9to5mac.com' },
      { protocol: 'https', hostname: '**.9to5google.com' },
      { protocol: 'https', hostname: '**.androidauthority.com' },
      { protocol: 'https', hostname: '**.macrumors.com' },
      { protocol: 'https', hostname: '**.appleinsider.com' },
      { protocol: 'https', hostname: '**.gsmarena.com' },
      { protocol: 'https', hostname: '**.pcmag.com' },
      { protocol: 'https', hostname: '**.tomshardware.com' },
      { protocol: 'https', hostname: '**.dev.to' },
      { protocol: 'https', hostname: '**.github.blog' },
      { protocol: 'https', hostname: '**.stackoverflow.blog' },
      { protocol: 'https', hostname: '**.hnrss.org' },
      { protocol: 'https', hostname: '**.freecodecamp.org' },
      { protocol: 'https', hostname: '**.smashingmagazine.com' },
      { protocol: 'https', hostname: '**.css-tricks.com' },
      { protocol: 'https', hostname: 'web.dev' },
      { protocol: 'https', hostname: '**.howtogeek.com' },
      { protocol: 'https', hostname: '**.makeuseof.com' },
      { protocol: 'https', hostname: '**.fastcompany.com' },
      { protocol: 'https', hostname: '**.theregister.com' },
      { protocol: 'https', hostname: '**.aws.amazon.com' },
      { protocol: 'https', hostname: 'blog.cloudflare.com' },
      { protocol: 'https', hostname: '**.nytimes.com' },
      { protocol: 'https', hostname: '**.pcworld.com' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: 'images.pexels.com' },
      { protocol: 'https', hostname: '**.pexels.com' },
      { protocol: 'https', hostname: '**.supabase.co' },
      { protocol: 'https', hostname: '**.supabase.storage' },
      { protocol: 'https', hostname: '**' },
    ],
  },
  experimental: {
    staleTimes: {
      dynamic: 300,
    },
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' https://*.googletagmanager.com https://va.vercel-scripts.com https://*.posthog.com",
              "connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://*.posthog.com https://*.supabase.co https://vitals.vercel-insights.com",
              "img-src 'self' data: https: blob:",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "font-src 'self' data: https://fonts.gstatic.com",
              "frame-src 'self' https://*.googletagmanager.com",
              "upgrade-insecure-requests",
            ].join('; '),
          },
        ],
      },
    ]
  },
};

export default nextConfig;
