/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: '**.theverge.com' },
      { protocol: 'https', hostname: '**.techcrunch.com' },
      { protocol: 'https', hostname: '**.wired.com' },
      { protocol: 'https', hostname: '**.engadget.com' },
      { protocol: 'https', hostname: '**.arstechnica.net' },
      { protocol: 'https', hostname: '**.arstechnica.com' },
      { protocol: 'https', hostname: '**.cnet.com' },
      { protocol: 'https', hostname: '**.zdnet.com' },
      { protocol: 'https', hostname: '**.gizmodo.com' },
      { protocol: 'https', hostname: '**.techradar.com' },
      { protocol: 'https', hostname: '**.mashable.com' },
      { protocol: 'https', hostname: '**.tomsguide.com' },
      { protocol: 'https', hostname: '**.technologyreview.com' },
      { protocol: 'https', hostname: '**.venturebeat.com' },
      { protocol: 'https', hostname: '**.bleepingcomputer.com' },
      { protocol: 'https', hostname: '**.securityweek.com' },
      { protocol: 'https', hostname: '**.krebsonsecurity.com' },
      { protocol: 'https', hostname: '**.threatpost.com' },
      { protocol: 'https', hostname: '**.9to5mac.com' },
      { protocol: 'https', hostname: '**.9to5google.com' },
      { protocol: 'https', hostname: '**.androidauthority.com' },
      { protocol: 'https', hostname: '**.macrumors.com' },
      { protocol: 'https', hostname: '**.appleinsider.com' },
      { protocol: 'https', hostname: '**.gsmarena.com' },
      { protocol: 'https', hostname: '**.pcmag.com' },
      { protocol: 'https', hostname: '**.tomshardware.com' },
      { protocol: 'https', hostname: '**.dev.to' },
      { protocol: 'https', hostname: '**.github.blog' },
      { protocol: 'https', hostname: '**.stackoverflow.blog' },
      { protocol: 'https', hostname: '**.hnrss.org' },
      { protocol: 'https', hostname: '**.freecodecamp.org' },
      { protocol: 'https', hostname: '**.smashingmagazine.com' },
      { protocol: 'https', hostname: '**.css-tricks.com' },
      { protocol: 'https', hostname: 'web.dev' },
      { protocol: 'https', hostname: '**.howtogeek.com' },
      { protocol: 'https', hostname: '**.makeuseof.com' },
      { protocol: 'https', hostname: '**.fastcompany.com' },
      { protocol: 'https', hostname: '**.theregister.com' },
      { protocol: 'https', hostname: '**.aws.amazon.com' },
      { protocol: 'https', hostname: 'blog.cloudflare.com' },
      { protocol: 'https', hostname: '**.nytimes.com' },
      { protocol: 'https', hostname: '**.pcworld.com' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: '**.supabase.co' },
      { protocol: 'https', hostname: '**.supabase.storage' },
      { protocol: 'https', hostname: '**' },
    ],
  },
};

export default nextConfig;
