/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    unoptimized: true,
    dangerouslyAllowSVG: true,
    remotePatterns: [
      { protocol: 'https', hostname: '**.theverge.com' },
      { protocol: 'https', hostname: '**.techcrunch.com' },
      { protocol: 'https', hostname: '**.wired.com' },
      { protocol: 'https', hostname: '**.engadget.com' },
      { protocol: 'https', hostname: '**.arstechnica.net' },
      { protocol: 'https', hostname: '**.arstechnica.com' },
      { protocol: 'https', hostname: '**.cnet.com' },
      { protocol: 'https', hostname: '**.zdnet.com' },
      { protocol: 'https', hostname: '**.gizmodo.com' },
      { protocol: 'https', hostname: '**.techradar.com' },
      { protocol: 'https', hostname: '**.mashable.com' },
      { protocol: 'https', hostname: '**.tomsguide.com' },
      { protocol: 'https', hostname: '**.technologyreview.com' },
      { protocol: 'https', hostname: '**.venturebeat.com' },
      { protocol: 'https', hostname: '**.bleepingcomputer.com' },
      { protocol: 'https', hostname: '**.securityweek.com' },
      { protocol: 'https', hostname: '**.krebsonsecurity.com' },
      { protocol: 'https', hostname: '**.threatpost.com' },
      { protocol: 'https', hostname: '**.9to5mac.com' },
      { protocol: 'https', hostname: '**.9to5google.com' },
      { protocol: 'https', hostname: '**.androidauthority.com' },
      { protocol: 'https', hostname: '**.macrumors.com' },
      { protocol: 'https', hostname: '**.appleinsider.com' },
      { protocol: 'https', hostname: '**.gsmarena.com' },
      { protocol: 'https', hostname: '**.pcmag.com' },
      { protocol: 'https', hostname: '**.tomshardware.com' },
      { protocol: 'https', hostname: '**.dev.to' },
      { protocol: 'https', hostname: '**.github.blog' },
      { protocol: 'https', hostname: '**.stackoverflow.blog' },
      { protocol: 'https', hostname: '**.hnrss.org' },
      { protocol: 'https', hostname: '**.freecodecamp.org' },
      { protocol: 'https', hostname: '**.smashingmagazine.com' },
      { protocol: 'https', hostname: '**.css-tricks.com' },
      { protocol: 'https', hostname: 'web.dev' },
      { protocol: 'https', hostname: '**.howtogeek.com' },
      { protocol: 'https', hostname: '**.makeuseof.com' },
      { protocol: 'https', hostname: '**.fastcompany.com' },
      { protocol: 'https', hostname: '**.theregister.com' },
      { protocol: 'https', hostname: '**.aws.amazon.com' },
      { protocol: 'https', hostname: 'blog.cloudflare.com' },
      { protocol: 'https', hostname: '**.nytimes.com' },
      { protocol: 'https', hostname: '**.pcworld.com' },
      { protocol: 'https', hostname: 'images.unsplash.com' },
      { protocol: 'https', hostname: 'images.pexels.com' },
      { protocol: 'https', hostname: '**.pexels.com' },
      { protocol: 'https', hostname: '**.supabase.co' },
      { protocol: 'https', hostname: '**.supabase.storage' },
      { protocol: 'https', hostname: '**' },
    ],
  },
  async headers() {
    const securityHeaders = [
      { key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' },
      { key: 'X-Content-Type-Options', value: 'nosniff' },
      { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
      { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
      { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), browsing-topics=(), interest-cohort=()' },
      { key: 'Cross-Origin-Opener-Policy', value: 'same-origin' },
      { key: 'Cross-Origin-Resource-Policy', value: 'same-origin' },
      { key: 'X-DNS-Prefetch-Control', value: 'on' },
    ]
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'Content-Security-Policy',
            value: [
              "default-src 'self'",
              "script-src 'self' 'unsafe-inline' https://*.googletagmanager.com https://va.vercel-scripts.com https://*.posthog.com https://pagead2.googlesyndication.com https://*.google.com https://challenges.cloudflare.com",
              "connect-src 'self' https://*.google-analytics.com https://*.analytics.google.com https://*.googletagmanager.com https://*.posthog.com https://*.supabase.co https://vitals.vercel-insights.com https://pagead2.googlesyndication.com",
              "img-src 'self' data: https: blob:",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "font-src 'self' data: https://fonts.gstatic.com",
              "frame-src 'self' https://*.googletagmanager.com https://googleads.g.doubleclick.net https://*.google.com https://www.youtube.com https://www.youtube-nocookie.com https://challenges.cloudflare.com",
              "upgrade-insecure-requests",
            ].join('; '),
          },
          ...securityHeaders,
        ],
      },
    ]
  },
};

export default nextConfig;
